project:
  type: website
  output-dir: docs


website:
  title: "George Steven Vega"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "TalentoTECH 2024"
        file: TalentoTECH/TalentoTECH.qmd  
      # - text: "Series de Tiempo"
      #   file: Series.qmd
      # - text: "Estadistica espacial"
      #   file: Espacial.qmd
      - about.qmd

  # sidebar:
  #     - title: "Series de Tiempo"
  #       style: "floating"
  #       collapse-level: 3
  #       sidebar: false
  #       background: light
  #       contents:
  #         - Series.qmd
  #         - Presentacion.qmd
  # 
  #     - title: "Estadistica espacial"
  #       contents:
  #         - Espacial.qmd
  #         - SpatioTemporal.qmd
  #         - Functional Kriging.qmd
          # navigation items

# website:
#   title: "George Steven Vega"
#   navbar:
#     background: primary
#     search: true
#     left:
#       - href: index.qmd
#         text: Home
#       - sidebar:Series de Tiempo
#       - sidebar:Estadistica espacial
#       - sidebar:about
#       
#   sidebar:
#       - id: Series de Tiempo
#         title: "Series de Tiempo"
#         style: "docked"
#         sidebar: false
#         background: light
#         collapse-level: 2
#         contents:
#           - Series.qmd
#           - Presentacion.qmd
#           
#       - id: Estadistica espacial
#         title: "Estadistica espacial"
#         contents:
#           - Espacial.qmd
          
#https://quarto.org/docs/websites/website-navigation.html
# website:
#   sidebar:
#     style: "docked"
#     search: true
#     contents:
#       - section: "Series de Tiempo"
#         contents:
#           - Presentacion.qmd
# 
#       - section: "Estadistica espacial"
#         contents:
#           - Espacial.qmd
#           
#       - section: "Index"
#         contents:
#           - index.qmd   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
