project:
  type: website
  output-dir: docs


website:
  title: "Georgie Steven Vega"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "TalentoTECH 2024"
        file: Descripcion.qmd
      # - text: "Series de Tiempo"
      #   file: Series.qmd
      # - text: "Estadistica espacial"
      #   file: Espacial.qmd
      - about.qmd

  sidebar:
      - title: "TalentoTECH 2024"
        style: "floating"
        collapse-level: 3
        sidebar: false
        background: light
        contents:
          - Descripcion.qmd
          - InformacionPersonal.qmd
          - InformacionContacto.qmd
          - InformacionSocioEco.qmd
          - InformacionSocioEco2.qmd
          - InformacionSocioEco3.qmd
         
          # navigation items


           
#       - id: Estadistica espacial
#         title: "Estadistica espacial"
#         contents:
#           - Espacial.qmd
          
#https://quarto.org/docs/websites/website-navigation.html
# website:
#   sidebar:
#     style: "docked"
#     search: true
#     contents:
#       - section: "Series de Tiempo"
#         contents:
#           - Presentacion.qmd
# 
#       - section: "Estadistica espacial"
#         contents:
#           - Espacial.qmd
#           
#       - section: "Index"
#         contents:
#           - index.qmd   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
